[runtime]
sampler = nautilus
verbosity = standard


; WARNING: Some of these likelihoods have data in common.
; You shouldn't use them all in a real pipeline - this is just for testing
[pipeline]
modules =  consistency  camb
    ;eboss16_elg_0
    ;eboss16_lrg_1
    ;eboss16_mgs
    eboss_rsd_lrg_mgs_qso_elg_gal
    ;eboss16_qso_1
timing=F
debug=F
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2 distances/rs_zdrag distances/h0rd
values = examples/rsd_f_sigma8_values.ini

[output]
filename = output/chains/eboss_rsd.txt

[test]
save_dir=output/bao
fatal_errors=T

[nautilus]
n_live = 1000
verbose = T
resume = T
; you can set this to T if you don't want 
privacy = F


[consistency]
file = utility/consistency/consistency_interface.py

[camb]
file = boltzmann/camb/camb_interface.py
mode = all
lmax = 2500          ;max ell to use for cmb calculation
feedback=0         ;amount of output to print
AccuracyBoost=1.0 ;CAMB accuracy boost parameter
do_tensors = F
do_lensing = F
NonLinear = none
zmin_background = 0.
zmax_background = 2.
nz_background = 201
use_ppf_w = T
kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700
; zmax is 100 for Euclid emulator.
;nz = 100

[camb_split]
file = boltzmann/camb/camb_interface_split.py
mode = all
#lmax = 396          ;max ell to use for cmb calculation, scale cut to exclude ISW
lmax = 2500         ;in this configuration the min is 2500
max_eta_k=500000
feedback=3         ;amount of output to print
AccuracyBoost=1.1 ;CAMB accuracy boost parameter
high_accuracy_default=T
do_tensors = True   ;include tensor modes
do_lensing = True    ;lensing is required w/ Planck data
NonLinear = none
; halofit_version = takahashi
accurate_massive_neutrino_transfers = T
theta_H0_range = "20 100"
zmin_background = 0.
zmax_background = 4.
nz_background = 401
;kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700
; zmax is 100 for Euclid emulator.
nz = 100
high_ell_template=$COSMOSIS_SRC_DIR/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat
; set these if you are doing lensing:
; lmax = 4500
; max_eta_k = 500000
; use_nonlinear_lensing = T

[euclid_emulator]
file = structure/EuclidEmulator2/euclid_emulator2_interface.py

[euclid_emulator_split]
file = structure/EuclidEmulator2/euclid_emulator2_interface_split.py

[boss_0]
file=likelihood/boss/boss_rsd.py
mode = 0
feedback = 1

[boss_1]
file=likelihood/boss/boss_rsd.py
mode = 1
feedback = 1

[boss_dr12_0]
file=likelihood/boss_dr12/boss_dr12.py
mode = 0
feedback = 1

[boss_dr12_1]
file=likelihood/boss_dr12/boss_dr12.py
mode = 1
feedback = 1

[des_y3_bao_1]
file=likelihood/des-y3-bao/bao_y3_like.py
chi2_column = 1
feedback = False

[des_y3_bao_2]
file=likelihood/des-y3-bao/bao_y3_like.py
chi2_column = 2
feedback = False

[des_y3_bao_3]
file=likelihood/des-y3-bao/bao_y3_like.py
chi2_column = 1
feedback = True

[des_y3_bao_4]
file=likelihood/des-y3-bao/bao_y3_like.py
chi2_column = 2
feedback = True

[eboss_lrg]
file=likelihood/eboss/lrg/eboss_dr14_lrg.py
verbose = True

[eboss_lya]
file=likelihood/eboss/lya/eboss_dr14_lya.py
feedback = True

[eboss16_boss_0]
file=likelihood/eboss_dr16/boss_dr12/boss_dr12_lrg_reanalyze.py
mode = 0
feedback = True

[eboss16_boss_1]
file=likelihood/eboss_dr16/boss_dr12/boss_dr12_lrg_reanalyze.py
mode = 1
feedback = True

[eboss16_elg_0]
file=likelihood/eboss_dr16/elg/eboss_dr16_elg.py
mode = 0
feedback = True

[eboss16_elg_1]
file=likelihood/eboss_dr16/elg/eboss_dr16_elg.py
mode = 1
feedback = True

[eboss16_lrg_0]
file=likelihood/eboss_dr16/lrg/eboss_dr16_lrg.py
mode = 0
feedback = True

[eboss16_lrg_1]
file=likelihood/eboss_dr16/lrg/eboss_dr16_lrg.py
mode = 1
feedback = True

[eboss16_lya]
file=likelihood/eboss_dr16/lya/eboss_dr16_lya.py
feedback = True

[eboss16_mgs]
file=likelihood/eboss_dr16/mgs/mgs.py
feedback = True

[eboss16_qso_0]
file=likelihood/eboss_dr16/qso/eboss_dr16_qso.py
mode = 0

[eboss16_qso_1]
file=likelihood/eboss_dr16/qso/eboss_dr16_qso.py
mode = 1

[eboss_rsd_lrg_mgs_qso_elg_gal]
file=likelihood/eboss_dr16/rsd/eboss_rsd_lrg_mgs_qso_elg_gal.py
feedback = F

[mgs]
file=likelihood/mgs_bao/mgs_bao.py
feedback = 1 

[wigglez]
file=likelihood/wigglez_bao/wigglez_bao.py
verbose = True

[desy3]
file=likelihood/des-y3-bao/bao_y3_like.py
feedback = T

[desy6]
file=likelihood/bao/des/y6/bao_y6_like.py
feedback = T

[desy6-5bin]
file=likelihood/bao/des/y6-5bin/bao_y6_5bins_like.py
feedback = T

