[runtime]
sampler = nautilus
verbosity = standard
resume = T

[pipeline]
modules =  consistency  camb
            ; sample_rdh 
            desi_split
timing=F
extra_output = distances/rs_zdrag distances/h0rd
values = examples/desi-values_split.ini
; It's worth switching this to T when sampling using multinest, polychord,
; or other samplers that can take advantage of differences in calculation speeds between
; different parameters.
fast_slow = T

[output]
filename =output/chains/3-split/desi-dr2-3-split-nu-fixed.txt
format=text

[nautilus]
n_live = 1000
verbose = T
resume = T

; you can set this to T if you don't want 
privacy = F

[emcee]
walkers = 32
samples = 300
nsteps = 10

[maxlike]
max_posterior = T

[test]
save_dir=output/desi
fatal_errors=T

[sample_rdh]
file = utility/rescale_distances_rdh/rescale_distances_rdh.py

[consistency]
file = utility/consistency/consistency_interface.py

[camb]
file = boltzmann/camb/camb_interface.py
mode = background
feedback = 0
AccuracyBoost = 1.0
zmin_background = 0.
zmax_background = 3.
nz_background = 301
use_ppf_w = T
want_chistar = F


[desi_split]
file = likelihood/bao/desi-dr2/desi_dr2_split.py
desi_data_sets = all
