[cosmological_parameters]
omega_m  =  0.1    0.3    0.9
h0  =  0.55    0.69    0.91 ; EuclidEmu 0.61-0.73

; If you fix w to -1.0 you can speed up the chain a bit
; by changing the astropy model parameter to lambdacdm.
omega_k  =  0.0
;w  =  -1.0
omega_b =  0.04  ; EuclidEmu 0.04-0.06

; CAMB requires these parameters to be set even
; if they are not used
A_s = 2.0e-9
n_s = 1.0
tau = 0.08

[supernova_params]
m  =  -21.0  -19.35  -18.0


