[runtime]
sampler = nautilus
root = ${PWD}
verbosity = standard

[test]
save_dir=output/planck
fatal_errors=T

[DEFAULT]
; This value is used below as %(planck_path)s
planck_path = likelihood/planck2018/baseline/plc_3.0

[pipeline]
; these names refer to sections later in the file:
modules = consistency
        camb_lin
        ;euclid_emulator
        ; standard Planck
        ;planck
        ; CMB Planck 2018 without lensing, scale cuts, free nuisance params
        p-TTTEEE-lowE-noT-cut
values = examples/planck_values.ini
priors = examples/omega-m-3-split-priors_Planck_nuisance.ini
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/S_8 data_vector/2pt_chi2
debug=T
timing=F
fast_slow = T

[output]
filename = output/chains/planck-cut-nuis-halofit.txt
format=text

[nautilus]
n_live = 2000
verbose = T
resume = True

[planck]
;Planck 2018 high ell TT,TE and EE + low ell TT + low ell EE (in Planck notations = TT+lowE)
;without CMB lensing
file = likelihood/planck2018/planck_interface.so
data_1 = %(planck_path)s/hi_l/plik_lite/plik_lite_v22_TTTEEE.clik
data_2 = %(planck_path)s/low_l/commander/commander_dx12_v3_2_29.clik
data_3 = %(planck_path)s/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik


[p-TTTEEE-lowE-noT-cut]
;Planck 2018 high ell TT,TE and EE + low ell TT + low ell EE (in Planck notations = TT+lowE)
;without CMB lensing
file = likelihood/planck2018/planck_interface.so
;high ell TT,TE and EE lite
data_1 = ${PLANCKPATH}/hi_l/plik/plik_rd12_HM_v22b_TTTEEE_cut.clik
;low ell EE 
data_2 = ${PLANCKPATH}/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik

; The consistency module translates between our chosen parameterization
; and any other that modules in the pipeline may want (e.g. camb)
[consistency]
file = ./utility/consistency/consistency_interface.py
;cosmomc_theta = T

[camb]
file = boltzmann/camb/camb_interface.py
mode = cmb
lmax = 2800          ;max ell to use for cmb calculation
feedback=1         ;amount of output to print
AccuracyBoost=1.0 ;CAMB accuracy boost parameter
do_tensors = True   ;include tensor modes
do_lensing = true    ;lensing is required w/ Planck data
NonLinear = lens
accurate_massive_neutrino_transfers = F
theta_H0_range = "20 100"

[camb_lin]
file = boltzmann/camb/camb_interface.py
mode = cmb
lmax = 2800          ;max ell to use for cmb calculation
feedback=1         ;amount of output to print
AccuracyBoost=1.0 ;CAMB accuracy boost parameter
do_tensors = True   ;include tensor modes
do_lensing = true    ;lensing is required w/ Planck data
NonLinear = none
; zmax is 100 for Euclid emulator.
nz = 100
accurate_massive_neutrino_transfers = T
theta_H0_range = "20 100"

[euclid_emulator]
file = structure/EuclidEmulator2/euclid_emulator2_interface.py

