[runtime]
sampler = nautilus
verbosity = standard
resume = T

[pipeline]
modules =  consistency  camb_split
           euclid_emulator_split
           growthfactor_split_early
           rsd_Blanchard
timing=F
extra_output = cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2
values = examples/rsd_f_sigma8_split_values.ini
fast_slow = T

[output]
filename = output/rsd-nu-fixed.txt

[nautilus]
n_live = 1000
verbose = T
resume = T

; you can set this to T if you don't want 
privacy = F

[emcee]
walkers = 32
samples = 300
nsteps = 10

[maxlike]
max_posterior = T

[test]
save_dir=output/desi
fatal_errors=T

[consistency]
file = utility/consistency/consistency_interface.py

[camb_split]
file = boltzmann/camb/camb_interface_split.py
mode = all
#lmax = 396          ;max ell to use for cmb calculation, scale cut to exclude ISW
lmax = 2500         ;in this configuration the min is 2500
max_eta_k=500000
feedback=3         ;amount of output to print
AccuracyBoost=1.1 ;CAMB accuracy boost parameter
high_accuracy_default=T
do_tensors = True   ;include tensor modes
do_lensing = True    ;lensing is required w/ Planck data
NonLinear = none
; halofit_version = takahashi
accurate_massive_neutrino_transfers = T
theta_H0_range = "20 100"
zmin_background = 0.
zmax_background = 4.
nz_background = 401
;kmin=1e-4
kmax = 50.0
kmax_extrapolate = 500.0
nk=700
; zmax is 100 for Euclid emulator.
nz = 100
high_ell_template=$COSMOSIS_SRC_DIR/boltzmann/camb/camb_Jan15/HighLExtrapTemplate_lenspotentialCls.dat
; set these if you are doing lensing:
; lmax = 4500
; max_eta_k = 500000
; use_nonlinear_lensing = T

[euclid_emulator_split]
file = structure/EuclidEmulator2/euclid_emulator2_interface_split.py

[growthfactor_split_early]
file = structure/growth_factor/growthfactor_split_early.py

[rsd_Blanchard]
file = likelihood/rsd/rsd_f_sigma8.py